eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  routes:
    player-server:
      path: /player-server/**
      url: http://player-server:8080/
      sensitive-headers:
    item-server:
      path: /item-server/**
      url: http://item-server:8080/
      sensitive-headers:
    match-server:
      path: /match-server/**
      url: http://match-server:8080/
      sensitive-headers:
    gamelogic-server:
      path: /gamelogic-server/**
      url: http://gamelogic-server:8080/
      sensitive-headers:
#    user-service:
#      path: /user-service/**
#      url: http://user-service:8080/
#      # Cookies are sensitive data. So, by default,
#      # Zool removes them when proxying.
#      # But here we need the cookies for authentication,
#      # so we need to allow them.
#      sensitive-headers:

server:
  port: 8080
  contextPath: /api/v1

spring:
  application:
    name: gateway
  rabbitmq:
    host: rabbitmq
  datasource:
    url: "jdbc:postgresql://postgres-user:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

security:
  sessions: ALWAYS

logging:
  level:
    org.springframework.security: debug
